### ISSUE TITLE
Dead ssl

### ISSUE THREAD

**Issue by bc1bb** [turt2live/evelium#102]
Cant connect to the example server because it has a dead ssl certificate

**Comment by turt2live** [comment]
The example itself doesn't really work either given the client is so early in development it can't even start up correctly. I'll fix the SSL though and maybe throw up a page that says it is not safe for usage.

**Comment by turt2live** [comment]
SSL should be fixed, although I generally caution against using the app for anything serious - it's unfortunately suffering from a bad case of Too Many Projects and Not Enough Time :(
